### ISSUE TITLE
Setup Sublime Text for JSX and ES6 syntax

### ISSUE THREAD

**Issue by msenyk** [msenyk/SFPermissionViewer#2]
Find out how to setup Sublime text for JSX + ES6 syntax highlight.

**Comment by OktavianRS** [comment]
# Highlighting JSX and ES6 syntax.

### 1)Open the "Command Palete..." via cmd + shft + p.

### 2)Select the Package Control: Install Package option, which can be found by typing "install".

### 3)Type in "Babel" and select the "Babel" package to install.

**Comment by OktavianRS** [comment]
## To set Babel as default syntax highlighter for .js and .jsx files by perform the following steps:

### 1)Open a file with the .js or .jsx extension.

### 2)Select  View -> Syntax -> Open all with current extension as... -> Babel -> JavaScript (Babel).

### 3)Repeat these steps for other file extensions.

**Comment by msenyk** [comment]
Well done!
The first step - install package control itself:
https://packagecontrol.io/installation
