### ISSUE TITLE
Create select Profile/Permission set component

### ISSUE THREAD

**Issue by msenyk** [msenyk/SFPermissionViewer#4]
Look at second picture from "Search Permissions" chapter.
This component is consists of:
- Title
- Table with 3 columns: Name, Type, Option
- Search field

Make sure that search text filter table rows and highlight matching words.
Mock server response will be provided later.

**Comment by OktavianRS** [comment]
Added new component "Search Permission" with table of dummy data and search functions. The search filters table rows and highlights matching letters.
Look at new branch "Profile/Permission".

**Comment by msenyk** [comment]
It works pretty good. I'm really impressed. However we cannot close this issue.
We should fix some drawbacks:
- It isn't a search permission view or component. We do not search anything. We just choose one profile or permission set from table. So, name of view file is wrong. Instead of view/SearchPermission.jsx it should be view/View.jsx. I'm sorry for such kind of tautology.
- Route to this page should be /view (not /search). When we choose certain profile we will go to the route /view/PROFILE_ID.
- Do not need to put link to /view as element of top level navigation bar. Permission Analyzer is a single link for now.
- Update home page and add button "View" that link to /view route and put to the right description text: "Choose profile or permission set and make sure what exactly they allow to do. All  permissions at the one page."
- Rename folder js/modules to js/components
- Selecting profile of permission set is just a first step of viewing permissions. We will use this table many times in our app. It is a great example to be a component. Move logic and markup of this table into component - js/components/SelectPermissionSet.jsx
- Inside view/View.jsx we have to see only references to components. Similar like:
  `<div>
  <Navbar />
  <SelectPermissionSet />
  </div>`
- Apply search and highlight for all columns of table (Name, Type and Option). Make this search case insensitive.

**Comment by msenyk** [comment]
Everything is fine. There is a small issue with search. It is still case sensitive. I am creating another issue for this task right now.
