### ISSUE TITLE
Make profile/permission set search case insensitive

### ISSUE THREAD

**Issue by msenyk** [msenyk/SFPermissionViewer#7]
We need to implement case insensitive search for SelectPermissionSet component.

Note, I've merged "Profile/View branch into master and delete old branches. Please, create new branch for this task from master with name "case-insensitive-search".

**Comment by OktavianRS** [comment]
I've fixed problem with case insensitive search. Please, have a look in your spare time at new branch "case-insensitive-search".

**Comment by msenyk** [comment]
It works perfectly. But it needs small code refactoring. See pull request.

**Comment by msenyk** [comment]
I've fixed the issue and update code to es6 classes.
